  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RDS_FTA"."FTA_RANGE_CLIENT" ("FOREST_FILE_ID", "CLIENT_NUMBER", "CLIENT_LOCN_CODE", "CLIENT_NAME", "FOREST_FILE_CLIENT_TYPE_CODE", "LICENSEE_START_DATE", "LICENSEE_END_DATE") AS 
  SELECT 
       PFU.FOREST_FILE_ID
     , FFC.CLIENT_NUMBER
     , FFC.CLIENT_LOCN_CODE
     , DECODE(VCP.CLIENT_TYPE_CODE,
              'I', VCP.CLIENT_NAME || ', ' || VCP.LEGAL_FIRST_NAME || ' ' || VCP.LEGAL_MIDDLE_NAME,
              VCP.CLIENT_NAME) CLIENT_NAME
     , FFC.FOREST_FILE_CLIENT_TYPE_CODE
     , FFC.LICENSEE_START_DATE
     , FFC.LICENSEE_END_DATE
FROM      MV_PROV_FOREST_USE    PFU
LEFT JOIN MV_FOREST_FILE_CLIENT FFC ON  FFC.FOREST_FILE_ID               = PFU.FOREST_FILE_ID
                                    AND FFC.FOREST_FILE_CLIENT_TYPE_CODE IN ('A','B')
LEFT JOIN MV_FOREST_CLIENT      VCP ON  VCP.CLIENT_NUMBER                = FFC.CLIENT_NUMBER
WHERE  PFU.FILE_STATUS_ST = 'A';
