  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RDS_FTA"."FTA_RANGE_LICENSEE" ("FOREST_FILE_ID", "FILE_STATUS_ST", "FILE_TYPE_CODE", "FILE_TYPE_DESC", "ORG_UNIT_CODE", "ROLLUP_REGION_CODE", "DISTRICT_ADMIN_ZONE", "ZONE_DESCRIPTION", "CONTACT", "CONTACT_PHONE_NUMBER", "CONTACT_EMAIL_ADDRESS", "LEGAL_EFFECTIVE_DT", "INITIAL_EXPIRY_DT", "CURRENT_EXPIRY_DT", "LICENSEE_START_DATE", "LICENSEE_END_DATE") AS 
  SELECT 
       PFU.FOREST_FILE_ID
     , PFU.FILE_STATUS_ST
     , PFU.FILE_TYPE_CODE
     , FTC.DESCRIPTION    AS FILE_TYPE_DESC
     , ORG.ORG_UNIT_CODE
     , ORG.ROLLUP_REGION_CODE
     , NVL(RTN.DISTRICT_ADMN_ZONE,PFU.DISTRICT_ADMIN_ZONE)  AS DISTRICT_ADMIN_ZONE
     , RGZ.ZONE_DESCRIPTION
     , RGZ.CONTACT
     , RGZ.CONTACT_PHONE_NUMBER
     , RGZ.CONTACT_EMAIL_ADDRESS
     , TTM.LEGAL_EFFECTIVE_DT
     , TTM.INITIAL_EXPIRY_DT
     , TTM.CURRENT_EXPIRY_DT
     , FFC.LICENSEE_START_DATE
     , FFC.LICENSEE_END_DATE
FROM      MV_PROV_FOREST_USE    PFU
LEFT JOIN MV_FILE_TYPE_CODE     FTC ON  FTC.FILE_TYPE_CODE               = PFU.FILE_TYPE_CODE
LEFT JOIN MV_RANGE_TENURE       RTN ON  RTN.FOREST_FILE_ID               = PFU.FOREST_FILE_ID
LEFT JOIN MV_TENURE_TERM        TTM ON  TTM.FOREST_FILE_ID               = PFU.FOREST_FILE_ID
LEFT JOIN MV_ORG_UNIT           ORG ON  ORG.ORG_UNIT_NO                  = RTN.ADMIN_FOREST_DISTRICT_NO
LEFT JOIN MV_FOREST_FILE_CLIENT FFC ON  FFC.FOREST_FILE_ID               = PFU.FOREST_FILE_ID
                                    AND FFC.FOREST_FILE_CLIENT_TYPE_CODE = 'A'
LEFT JOIN MV_RANGE_ZONE         RGZ ON  RGZ.ADMIN_FOREST_DISTRICT_NO     = RTN.ADMIN_FOREST_DISTRICT_NO
                                    AND RGZ.RANGE_ZONE_CODE              = NVL(RTN.DISTRICT_ADMN_ZONE,PFU.DISTRICT_ADMIN_ZONE)
WHERE  PFU.FILE_STATUS_ST = 'A';
