  CREATE OR REPLACE FORCE EDITIONABLE VIEW "RDS_FTA"."FTA_RANGE_USAGE" ("FOREST_FILE_ID", "CALENDAR_YEAR", "AUTHORIZED_USE", "NON_USE_NONBILLABLE", "NON_USE_BILLABLE", "TEMP_INCREASE", "TOTAL_ANNUAL_USE") AS 
  SELECT
       PFU.FOREST_FILE_ID
     , RPV.CALENDAR_YEAR
     , RPV.AUTHORIZED_USE
     , RPV.NON_USE_NONBILLABLE
     , RPV.NON_USE_BILLABLE
     , RPV.TEMP_INCREASE
     , RPV.TOTAL_ANNUAL_USE
FROM      MV_PROV_FOREST_USE    PFU
LEFT JOIN MV_RANGE_TENURE       RTN ON  RTN.FOREST_FILE_ID               = PFU.FOREST_FILE_ID
LEFT JOIN MV_RANGE_PROVISION    RPV ON  RPV.FOREST_FILE_ID               = RTN.FOREST_FILE_ID
WHERE  PFU.FILE_STATUS_ST = 'A' ;
