---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-build-template"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${SOURCE_IMAGE_NAME}
    creationTimestamp: null
    annotations:
      description: Nodejs Base Image
    labels:
      shared: 'true'
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: ${SOURCE_IMAGE_TAG}
      annotations: null
      from:
        kind: DockerImage
        name: ${BASE_IMAGE_URL}
      importPolicy: {}
      referencePolicy:
        type: Local
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    triggers:
    - type: ImageChange
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${GIT_REPO_URL}"
        ref: "${GIT_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: "${SOURCE_IMAGE_KIND}"
          name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${OUTPUT_IMAGE_TAG}"
    resources:
      requests:
        cpu: "${CPU_REQUEST}"
        memory: "${MEMORY_REQUEST}"
      limits:
        cpu: "${CPU_LIMIT}"
        memory: "${MEMORY_LIMIT}"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: bctw-api
- name: GIT_REPO_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/range-api.git
- name: GIT_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: dev
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: true
  value: "./"
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
    DockerImage.
  required: true
  value: ImageStreamTag
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the source image.
  required: true
  value: nodejs-6-base
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  description: The tag of the source image.
  required: true
  value: latest
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: true
  value: latest
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: 250m
- name: BASE_IMAGE_URL
  displayName: base image url
  requried: true
  value:  registry.redhat.io/rhscl/nodejs-6-rhel7
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: 1000m
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 100Mi
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 2Gi
